Repository erda-project/beats, pull requests merged in 2021-09, with the labels that each got.

#32 bugfix: parse_message failed to match multiline
  filebeat/processor/parser/parse_message.go
  filebeat/processor/parser/parse_message_test.go
Labels: bug

#33 bugfix: parse_message failed to match multiline
  filebeat/processor/parser/parse_message.go
  filebeat/processor/parser/parse_message_test.go
Labels: bug

#34 bugfix: parse_message failed to match multiline
  filebeat/processor/parser/parse_message.go
  filebeat/processor/parser/parse_message_test.go
Labels: bug

#35 Log env
  filebeat/conf/erda_on_erda.yml
  filebeat/conf/filebeat.yml
Labels: approved

#36 feature: add option to disable log-analytics output (#27)
  filebeat/conf/erda_on_erda.yml
  filebeat/conf/filebeat.yml
  filebeat/processor/add_terminus_metadata/add_terminus_metadata.go
  filebeat/processor/add_terminus_metadata/config.go
Labels: enhancement

#37 feature: change docker image source of golang:1.15.11
  Dockerfile
Labels: approved
